stocks:
  ["EEM",
  "SPY",
  "GDX",
  "XLF",
  "XOP",
  "AMLP",
  "FXI",
  "QQQ",
  "EWZ",
  "EFA",
  "USO",
  "HYG",
  "IAU",
  "IWM",
  "XLE",
  "XLU",
  "IEMG",
  "GDXJ",
  "SLV",
  "VWO",
  "XLP",
  "XLI",
  "OIH",
  "LQD",
  "XLK",
  "VEA",
  "TLT",
  "IEFA",
  "XLV",
  "EWJ",
  "GLD",
  "IYR",
  "BKLN",
  "EWH",
  "ASHR",
  "XLB",
  "RSX",
  "JNK",
  "KRE",
  "XBI",
  "AGG",
  "VNQ",
  "GOVT",
  "UNG",
  "IVV",
  "XLY",
  "EWT",
  "PFF",
  "XLRE",
  "MCHI",
  "INDA",
  "BND",
  "USMV",
  "EZU",
  "SMH",
  "XRT",
  "EWY",
  "IEF",
  "SPLV",
  "XLC",
  "IJR",
  "VIXY",
  "EWG",
  "EWW",
  "VTI",
  "VGK",
  "IBB",
  "PGX",
  "VOO",
  "EMB",
  "SCHF",
  "VEU",
  "SJNK",
  "EMLC",
  "XME",
  "DIA",
  "EWA",
  "VCSH",
  "JPST",
  "MLPA",
  "VCIT",
  "ITB",
  "ACWI",
  "KWEB",
  "EWC",
  "EWU",
  "BNDX",
  "SHY",
  "VT",
  "IWD",
  "VXUS",
  "MBB",
  "ACWX",
  "XHB",
  "BSV",
  "SHV",
  "FEZ",
  "IWF",
  "IGSB",
  "SPYV",
  "ITOT",
  "FPE",
  "FVD",
  "SHYG",
  "VYM",
  "BBJP",
  "DGRO",
  "KBE",
  "VTV",
  "SPAB",
  "SPIB",
  "IWR",
  "DBC",
  "BIL",
  "SPSB",
  "FLOT",
  "GLDM",
  "VIG",
  "XES",
  "SCHE",
  "TIP",
  "PDBC",
  "SPYG",
  "MINT",
  "SCZ",
  "SPDW",
  "PCY",
  "USHY",
  "IXUS",
  "NEAR",
  "EPI",
  "SPLG",
  "HYLB",
  "AAXJ",
  "SPEM",
  "VMBS",
  "BIV",
  "QUAL",
  "ILF",
  "EWP"]